name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - run: chmod +x gradlew

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
          arguments: build
