name: Release

on:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - run: chmod +x gradlew

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: bootJar

      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.GITHUB_REF_NAME }}
          files: build/libs/MDC-Bot-*.jar
